version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name work-last-App --s3-location s3://work-last-bucket/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src
